name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: water-bill-calculator
        path: app/build/outputs/apk/release/app-release-unsigned.apk
